//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace ETFTrans.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tipPretraga", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    public partial class tipPretraga : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal CijenaField;
        
        private System.Collections.ObjectModel.ObservableCollection<string> ListaDanaVoznje1Field;
        
        private System.Collections.ObjectModel.ObservableCollection<string> ListaStanica1Field;
        
        private string OdredisteField;
        
        private string PolazisteField;
        
        private System.DateTime VrijemeDolaskaField;
        
        private System.DateTime VrijemePolaskaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cijena {
            get {
                return this.CijenaField;
            }
            set {
                if ((this.CijenaField.Equals(value) != true)) {
                    this.CijenaField = value;
                    this.RaisePropertyChanged("Cijena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<string> ListaDanaVoznje1 {
            get {
                return this.ListaDanaVoznje1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ListaDanaVoznje1Field, value) != true)) {
                    this.ListaDanaVoznje1Field = value;
                    this.RaisePropertyChanged("ListaDanaVoznje1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<string> ListaStanica1 {
            get {
                return this.ListaStanica1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ListaStanica1Field, value) != true)) {
                    this.ListaStanica1Field = value;
                    this.RaisePropertyChanged("ListaStanica1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Odrediste {
            get {
                return this.OdredisteField;
            }
            set {
                if ((object.ReferenceEquals(this.OdredisteField, value) != true)) {
                    this.OdredisteField = value;
                    this.RaisePropertyChanged("Odrediste");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Polaziste {
            get {
                return this.PolazisteField;
            }
            set {
                if ((object.ReferenceEquals(this.PolazisteField, value) != true)) {
                    this.PolazisteField = value;
                    this.RaisePropertyChanged("Polaziste");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime VrijemeDolaska {
            get {
                return this.VrijemeDolaskaField;
            }
            set {
                if ((this.VrijemeDolaskaField.Equals(value) != true)) {
                    this.VrijemeDolaskaField = value;
                    this.RaisePropertyChanged("VrijemeDolaska");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime VrijemePolaska {
            get {
                return this.VrijemePolaskaField;
            }
            set {
                if ((this.VrijemePolaskaField.Equals(value) != true)) {
                    this.VrijemePolaskaField = value;
                    this.RaisePropertyChanged("VrijemePolaska");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Iservis")]
    public interface Iservis {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iservis/pretrazi", ReplyAction="http://tempuri.org/Iservis/pretraziResponse")]
        System.IAsyncResult Beginpretrazi(string polaziste, string odrediste, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<ETFTrans.ServiceReference1.tipPretraga> Endpretrazi(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IservisChannel : ETFTrans.ServiceReference1.Iservis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class pretraziCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public pretraziCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<ETFTrans.ServiceReference1.tipPretraga> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<ETFTrans.ServiceReference1.tipPretraga>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IservisClient : System.ServiceModel.ClientBase<ETFTrans.ServiceReference1.Iservis>, ETFTrans.ServiceReference1.Iservis {
        
        private BeginOperationDelegate onBeginpretraziDelegate;
        
        private EndOperationDelegate onEndpretraziDelegate;
        
        private System.Threading.SendOrPostCallback onpretraziCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public IservisClient() {
        }
        
        public IservisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IservisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IservisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IservisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<pretraziCompletedEventArgs> pretraziCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ETFTrans.ServiceReference1.Iservis.Beginpretrazi(string polaziste, string odrediste, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginpretrazi(polaziste, odrediste, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<ETFTrans.ServiceReference1.tipPretraga> ETFTrans.ServiceReference1.Iservis.Endpretrazi(System.IAsyncResult result) {
            return base.Channel.Endpretrazi(result);
        }
        
        private System.IAsyncResult OnBeginpretrazi(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string polaziste = ((string)(inValues[0]));
            string odrediste = ((string)(inValues[1]));
            return ((ETFTrans.ServiceReference1.Iservis)(this)).Beginpretrazi(polaziste, odrediste, callback, asyncState);
        }
        
        private object[] OnEndpretrazi(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<ETFTrans.ServiceReference1.tipPretraga> retVal = ((ETFTrans.ServiceReference1.Iservis)(this)).Endpretrazi(result);
            return new object[] {
                    retVal};
        }
        
        private void OnpretraziCompleted(object state) {
            if ((this.pretraziCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.pretraziCompleted(this, new pretraziCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void pretraziAsync(string polaziste, string odrediste) {
            this.pretraziAsync(polaziste, odrediste, null);
        }
        
        public void pretraziAsync(string polaziste, string odrediste, object userState) {
            if ((this.onBeginpretraziDelegate == null)) {
                this.onBeginpretraziDelegate = new BeginOperationDelegate(this.OnBeginpretrazi);
            }
            if ((this.onEndpretraziDelegate == null)) {
                this.onEndpretraziDelegate = new EndOperationDelegate(this.OnEndpretrazi);
            }
            if ((this.onpretraziCompletedDelegate == null)) {
                this.onpretraziCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnpretraziCompleted);
            }
            base.InvokeAsync(this.onBeginpretraziDelegate, new object[] {
                        polaziste,
                        odrediste}, this.onEndpretraziDelegate, this.onpretraziCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ETFTrans.ServiceReference1.Iservis CreateChannel() {
            return new IservisClientChannel(this);
        }
        
        private class IservisClientChannel : ChannelBase<ETFTrans.ServiceReference1.Iservis>, ETFTrans.ServiceReference1.Iservis {
            
            public IservisClientChannel(System.ServiceModel.ClientBase<ETFTrans.ServiceReference1.Iservis> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult Beginpretrazi(string polaziste, string odrediste, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = polaziste;
                _args[1] = odrediste;
                System.IAsyncResult _result = base.BeginInvoke("pretrazi", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<ETFTrans.ServiceReference1.tipPretraga> Endpretrazi(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<ETFTrans.ServiceReference1.tipPretraga> _result = ((System.Collections.ObjectModel.ObservableCollection<ETFTrans.ServiceReference1.tipPretraga>)(base.EndInvoke("pretrazi", _args, result)));
                return _result;
            }
        }
    }
}
