#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ETFTransBaza")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDaniVoznjeLinije(DaniVoznjeLinije instance);
    partial void UpdateDaniVoznjeLinije(DaniVoznjeLinije instance);
    partial void DeleteDaniVoznjeLinije(DaniVoznjeLinije instance);
    partial void InsertDatumPolaskaLinije(DatumPolaskaLinije instance);
    partial void UpdateDatumPolaskaLinije(DatumPolaskaLinije instance);
    partial void DeleteDatumPolaskaLinije(DatumPolaskaLinije instance);
    partial void InsertLinija(Linija instance);
    partial void UpdateLinija(Linija instance);
    partial void DeleteLinija(Linija instance);
    partial void InsertStanicaLinija(StanicaLinija instance);
    partial void UpdateStanicaLinija(StanicaLinija instance);
    partial void DeleteStanicaLinija(StanicaLinija instance);
    partial void InsertStanica(Stanica instance);
    partial void UpdateStanica(Stanica instance);
    partial void DeleteStanica(Stanica instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ETFTransBazaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DaniVoznjeLinije> DaniVoznjeLinijes
		{
			get
			{
				return this.GetTable<DaniVoznjeLinije>();
			}
		}
		
		public System.Data.Linq.Table<DatumPolaskaLinije> DatumPolaskaLinijes
		{
			get
			{
				return this.GetTable<DatumPolaskaLinije>();
			}
		}
		
		public System.Data.Linq.Table<Linija> Linijas
		{
			get
			{
				return this.GetTable<Linija>();
			}
		}
		
		public System.Data.Linq.Table<StanicaLinija> StanicaLinijas
		{
			get
			{
				return this.GetTable<StanicaLinija>();
			}
		}
		
		public System.Data.Linq.Table<Stanica> Stanicas
		{
			get
			{
				return this.GetTable<Stanica>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DaniVoznjeLinije")]
	public partial class DaniVoznjeLinije : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DaniVoznjeLinijeId;
		
		private bool _pon;
		
		private bool _uto;
		
		private bool _sri;
		
		private bool _cet;
		
		private bool _pet;
		
		private bool _sub;
		
		private bool _ned;
		
		private EntitySet<Linija> _Linijas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDaniVoznjeLinijeIdChanging(int value);
    partial void OnDaniVoznjeLinijeIdChanged();
    partial void OnponChanging(bool value);
    partial void OnponChanged();
    partial void OnutoChanging(bool value);
    partial void OnutoChanged();
    partial void OnsriChanging(bool value);
    partial void OnsriChanged();
    partial void OncetChanging(bool value);
    partial void OncetChanged();
    partial void OnpetChanging(bool value);
    partial void OnpetChanged();
    partial void OnsubChanging(bool value);
    partial void OnsubChanged();
    partial void OnnedChanging(bool value);
    partial void OnnedChanged();
    #endregion
		
		public DaniVoznjeLinije()
		{
			this._Linijas = new EntitySet<Linija>(new Action<Linija>(this.attach_Linijas), new Action<Linija>(this.detach_Linijas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaniVoznjeLinijeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DaniVoznjeLinijeId
		{
			get
			{
				return this._DaniVoznjeLinijeId;
			}
			set
			{
				if ((this._DaniVoznjeLinijeId != value))
				{
					this.OnDaniVoznjeLinijeIdChanging(value);
					this.SendPropertyChanging();
					this._DaniVoznjeLinijeId = value;
					this.SendPropertyChanged("DaniVoznjeLinijeId");
					this.OnDaniVoznjeLinijeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pon", DbType="Bit NOT NULL")]
		public bool pon
		{
			get
			{
				return this._pon;
			}
			set
			{
				if ((this._pon != value))
				{
					this.OnponChanging(value);
					this.SendPropertyChanging();
					this._pon = value;
					this.SendPropertyChanged("pon");
					this.OnponChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uto", DbType="Bit NOT NULL")]
		public bool uto
		{
			get
			{
				return this._uto;
			}
			set
			{
				if ((this._uto != value))
				{
					this.OnutoChanging(value);
					this.SendPropertyChanging();
					this._uto = value;
					this.SendPropertyChanged("uto");
					this.OnutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sri", DbType="Bit NOT NULL")]
		public bool sri
		{
			get
			{
				return this._sri;
			}
			set
			{
				if ((this._sri != value))
				{
					this.OnsriChanging(value);
					this.SendPropertyChanging();
					this._sri = value;
					this.SendPropertyChanged("sri");
					this.OnsriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cet", DbType="Bit NOT NULL")]
		public bool cet
		{
			get
			{
				return this._cet;
			}
			set
			{
				if ((this._cet != value))
				{
					this.OncetChanging(value);
					this.SendPropertyChanging();
					this._cet = value;
					this.SendPropertyChanged("cet");
					this.OncetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pet", DbType="Bit NOT NULL")]
		public bool pet
		{
			get
			{
				return this._pet;
			}
			set
			{
				if ((this._pet != value))
				{
					this.OnpetChanging(value);
					this.SendPropertyChanging();
					this._pet = value;
					this.SendPropertyChanged("pet");
					this.OnpetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sub", DbType="Bit NOT NULL")]
		public bool sub
		{
			get
			{
				return this._sub;
			}
			set
			{
				if ((this._sub != value))
				{
					this.OnsubChanging(value);
					this.SendPropertyChanging();
					this._sub = value;
					this.SendPropertyChanged("sub");
					this.OnsubChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ned", DbType="Bit NOT NULL")]
		public bool ned
		{
			get
			{
				return this._ned;
			}
			set
			{
				if ((this._ned != value))
				{
					this.OnnedChanging(value);
					this.SendPropertyChanging();
					this._ned = value;
					this.SendPropertyChanged("ned");
					this.OnnedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DaniVoznjeLinije_Linija", Storage="_Linijas", ThisKey="DaniVoznjeLinijeId", OtherKey="daniVoznje_DaniVoznjeLinijeId")]
		public EntitySet<Linija> Linijas
		{
			get
			{
				return this._Linijas;
			}
			set
			{
				this._Linijas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Linijas(Linija entity)
		{
			this.SendPropertyChanging();
			entity.DaniVoznjeLinije = this;
		}
		
		private void detach_Linijas(Linija entity)
		{
			this.SendPropertyChanging();
			entity.DaniVoznjeLinije = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DatumPolaskaLinije")]
	public partial class DatumPolaskaLinije : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DatumPolaskaLinijeId;
		
		private System.DateTime _datumPolaska;
		
		private int _brojSlobodnihMjesta;
		
		private System.Nullable<int> _datumPolaskaZaLiniju_LinijaID;
		
		private EntityRef<Linija> _Linija;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDatumPolaskaLinijeIdChanging(int value);
    partial void OnDatumPolaskaLinijeIdChanged();
    partial void OndatumPolaskaChanging(System.DateTime value);
    partial void OndatumPolaskaChanged();
    partial void OnbrojSlobodnihMjestaChanging(int value);
    partial void OnbrojSlobodnihMjestaChanged();
    partial void OndatumPolaskaZaLiniju_LinijaIDChanging(System.Nullable<int> value);
    partial void OndatumPolaskaZaLiniju_LinijaIDChanged();
    #endregion
		
		public DatumPolaskaLinije()
		{
			this._Linija = default(EntityRef<Linija>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatumPolaskaLinijeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DatumPolaskaLinijeId
		{
			get
			{
				return this._DatumPolaskaLinijeId;
			}
			set
			{
				if ((this._DatumPolaskaLinijeId != value))
				{
					this.OnDatumPolaskaLinijeIdChanging(value);
					this.SendPropertyChanging();
					this._DatumPolaskaLinijeId = value;
					this.SendPropertyChanged("DatumPolaskaLinijeId");
					this.OnDatumPolaskaLinijeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datumPolaska", DbType="DateTime NOT NULL")]
		public System.DateTime datumPolaska
		{
			get
			{
				return this._datumPolaska;
			}
			set
			{
				if ((this._datumPolaska != value))
				{
					this.OndatumPolaskaChanging(value);
					this.SendPropertyChanging();
					this._datumPolaska = value;
					this.SendPropertyChanged("datumPolaska");
					this.OndatumPolaskaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brojSlobodnihMjesta", DbType="Int NOT NULL")]
		public int brojSlobodnihMjesta
		{
			get
			{
				return this._brojSlobodnihMjesta;
			}
			set
			{
				if ((this._brojSlobodnihMjesta != value))
				{
					this.OnbrojSlobodnihMjestaChanging(value);
					this.SendPropertyChanging();
					this._brojSlobodnihMjesta = value;
					this.SendPropertyChanged("brojSlobodnihMjesta");
					this.OnbrojSlobodnihMjestaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datumPolaskaZaLiniju_LinijaID", DbType="Int")]
		public System.Nullable<int> datumPolaskaZaLiniju_LinijaID
		{
			get
			{
				return this._datumPolaskaZaLiniju_LinijaID;
			}
			set
			{
				if ((this._datumPolaskaZaLiniju_LinijaID != value))
				{
					if (this._Linija.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndatumPolaskaZaLiniju_LinijaIDChanging(value);
					this.SendPropertyChanging();
					this._datumPolaskaZaLiniju_LinijaID = value;
					this.SendPropertyChanged("datumPolaskaZaLiniju_LinijaID");
					this.OndatumPolaskaZaLiniju_LinijaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Linija_DatumPolaskaLinije", Storage="_Linija", ThisKey="datumPolaskaZaLiniju_LinijaID", OtherKey="LinijaID", IsForeignKey=true)]
		public Linija Linija
		{
			get
			{
				return this._Linija.Entity;
			}
			set
			{
				Linija previousValue = this._Linija.Entity;
				if (((previousValue != value) 
							|| (this._Linija.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Linija.Entity = null;
						previousValue.DatumPolaskaLinijes.Remove(this);
					}
					this._Linija.Entity = value;
					if ((value != null))
					{
						value.DatumPolaskaLinijes.Add(this);
						this._datumPolaskaZaLiniju_LinijaID = value.LinijaID;
					}
					else
					{
						this._datumPolaskaZaLiniju_LinijaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Linija");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Linija")]
	public partial class Linija : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LinijaID;
		
		private System.DateTime _vrijemePolaska;
		
		private System.DateTime _vrijemeDolaska;
		
		private string _odredisteLinije;
		
		private decimal _cijenaZaGlavnoOdrediste;
		
		private int _brojSlobodnihMjesta;
		
		private int _brojRaspolozivihMjesta;
		
		private string _tipLinije;
		
		private System.Nullable<int> _daniVoznje_DaniVoznjeLinijeId;
		
		private EntitySet<DatumPolaskaLinije> _DatumPolaskaLinijes;
		
		private EntitySet<StanicaLinija> _StanicaLinijas;
		
		private EntityRef<DaniVoznjeLinije> _DaniVoznjeLinije;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLinijaIDChanging(int value);
    partial void OnLinijaIDChanged();
    partial void OnvrijemePolaskaChanging(System.DateTime value);
    partial void OnvrijemePolaskaChanged();
    partial void OnvrijemeDolaskaChanging(System.DateTime value);
    partial void OnvrijemeDolaskaChanged();
    partial void OnodredisteLinijeChanging(string value);
    partial void OnodredisteLinijeChanged();
    partial void OncijenaZaGlavnoOdredisteChanging(decimal value);
    partial void OncijenaZaGlavnoOdredisteChanged();
    partial void OnbrojSlobodnihMjestaChanging(int value);
    partial void OnbrojSlobodnihMjestaChanged();
    partial void OnbrojRaspolozivihMjestaChanging(int value);
    partial void OnbrojRaspolozivihMjestaChanged();
    partial void OntipLinijeChanging(string value);
    partial void OntipLinijeChanged();
    partial void OndaniVoznje_DaniVoznjeLinijeIdChanging(System.Nullable<int> value);
    partial void OndaniVoznje_DaniVoznjeLinijeIdChanged();
    #endregion
		
		public Linija()
		{
			this._DatumPolaskaLinijes = new EntitySet<DatumPolaskaLinije>(new Action<DatumPolaskaLinije>(this.attach_DatumPolaskaLinijes), new Action<DatumPolaskaLinije>(this.detach_DatumPolaskaLinijes));
			this._StanicaLinijas = new EntitySet<StanicaLinija>(new Action<StanicaLinija>(this.attach_StanicaLinijas), new Action<StanicaLinija>(this.detach_StanicaLinijas));
			this._DaniVoznjeLinije = default(EntityRef<DaniVoznjeLinije>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinijaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LinijaID
		{
			get
			{
				return this._LinijaID;
			}
			set
			{
				if ((this._LinijaID != value))
				{
					this.OnLinijaIDChanging(value);
					this.SendPropertyChanging();
					this._LinijaID = value;
					this.SendPropertyChanged("LinijaID");
					this.OnLinijaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vrijemePolaska", DbType="DateTime NOT NULL")]
		public System.DateTime vrijemePolaska
		{
			get
			{
				return this._vrijemePolaska;
			}
			set
			{
				if ((this._vrijemePolaska != value))
				{
					this.OnvrijemePolaskaChanging(value);
					this.SendPropertyChanging();
					this._vrijemePolaska = value;
					this.SendPropertyChanged("vrijemePolaska");
					this.OnvrijemePolaskaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vrijemeDolaska", DbType="DateTime NOT NULL")]
		public System.DateTime vrijemeDolaska
		{
			get
			{
				return this._vrijemeDolaska;
			}
			set
			{
				if ((this._vrijemeDolaska != value))
				{
					this.OnvrijemeDolaskaChanging(value);
					this.SendPropertyChanging();
					this._vrijemeDolaska = value;
					this.SendPropertyChanged("vrijemeDolaska");
					this.OnvrijemeDolaskaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odredisteLinije", DbType="NVarChar(MAX)")]
		public string odredisteLinije
		{
			get
			{
				return this._odredisteLinije;
			}
			set
			{
				if ((this._odredisteLinije != value))
				{
					this.OnodredisteLinijeChanging(value);
					this.SendPropertyChanging();
					this._odredisteLinije = value;
					this.SendPropertyChanged("odredisteLinije");
					this.OnodredisteLinijeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cijenaZaGlavnoOdrediste", DbType="Decimal(18,2) NOT NULL")]
		public decimal cijenaZaGlavnoOdrediste
		{
			get
			{
				return this._cijenaZaGlavnoOdrediste;
			}
			set
			{
				if ((this._cijenaZaGlavnoOdrediste != value))
				{
					this.OncijenaZaGlavnoOdredisteChanging(value);
					this.SendPropertyChanging();
					this._cijenaZaGlavnoOdrediste = value;
					this.SendPropertyChanged("cijenaZaGlavnoOdrediste");
					this.OncijenaZaGlavnoOdredisteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brojSlobodnihMjesta", DbType="Int NOT NULL")]
		public int brojSlobodnihMjesta
		{
			get
			{
				return this._brojSlobodnihMjesta;
			}
			set
			{
				if ((this._brojSlobodnihMjesta != value))
				{
					this.OnbrojSlobodnihMjestaChanging(value);
					this.SendPropertyChanging();
					this._brojSlobodnihMjesta = value;
					this.SendPropertyChanged("brojSlobodnihMjesta");
					this.OnbrojSlobodnihMjestaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brojRaspolozivihMjesta", DbType="Int NOT NULL")]
		public int brojRaspolozivihMjesta
		{
			get
			{
				return this._brojRaspolozivihMjesta;
			}
			set
			{
				if ((this._brojRaspolozivihMjesta != value))
				{
					this.OnbrojRaspolozivihMjestaChanging(value);
					this.SendPropertyChanging();
					this._brojRaspolozivihMjesta = value;
					this.SendPropertyChanged("brojRaspolozivihMjesta");
					this.OnbrojRaspolozivihMjestaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipLinije", DbType="NVarChar(MAX)")]
		public string tipLinije
		{
			get
			{
				return this._tipLinije;
			}
			set
			{
				if ((this._tipLinije != value))
				{
					this.OntipLinijeChanging(value);
					this.SendPropertyChanging();
					this._tipLinije = value;
					this.SendPropertyChanged("tipLinije");
					this.OntipLinijeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daniVoznje_DaniVoznjeLinijeId", DbType="Int")]
		public System.Nullable<int> daniVoznje_DaniVoznjeLinijeId
		{
			get
			{
				return this._daniVoznje_DaniVoznjeLinijeId;
			}
			set
			{
				if ((this._daniVoznje_DaniVoznjeLinijeId != value))
				{
					if (this._DaniVoznjeLinije.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndaniVoznje_DaniVoznjeLinijeIdChanging(value);
					this.SendPropertyChanging();
					this._daniVoznje_DaniVoznjeLinijeId = value;
					this.SendPropertyChanged("daniVoznje_DaniVoznjeLinijeId");
					this.OndaniVoznje_DaniVoznjeLinijeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Linija_DatumPolaskaLinije", Storage="_DatumPolaskaLinijes", ThisKey="LinijaID", OtherKey="datumPolaskaZaLiniju_LinijaID")]
		public EntitySet<DatumPolaskaLinije> DatumPolaskaLinijes
		{
			get
			{
				return this._DatumPolaskaLinijes;
			}
			set
			{
				this._DatumPolaskaLinijes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Linija_StanicaLinija", Storage="_StanicaLinijas", ThisKey="LinijaID", OtherKey="Linija_LinijaID")]
		public EntitySet<StanicaLinija> StanicaLinijas
		{
			get
			{
				return this._StanicaLinijas;
			}
			set
			{
				this._StanicaLinijas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DaniVoznjeLinije_Linija", Storage="_DaniVoznjeLinije", ThisKey="daniVoznje_DaniVoznjeLinijeId", OtherKey="DaniVoznjeLinijeId", IsForeignKey=true)]
		public DaniVoznjeLinije DaniVoznjeLinije
		{
			get
			{
				return this._DaniVoznjeLinije.Entity;
			}
			set
			{
				DaniVoznjeLinije previousValue = this._DaniVoznjeLinije.Entity;
				if (((previousValue != value) 
							|| (this._DaniVoznjeLinije.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DaniVoznjeLinije.Entity = null;
						previousValue.Linijas.Remove(this);
					}
					this._DaniVoznjeLinije.Entity = value;
					if ((value != null))
					{
						value.Linijas.Add(this);
						this._daniVoznje_DaniVoznjeLinijeId = value.DaniVoznjeLinijeId;
					}
					else
					{
						this._daniVoznje_DaniVoznjeLinijeId = default(Nullable<int>);
					}
					this.SendPropertyChanged("DaniVoznjeLinije");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DatumPolaskaLinijes(DatumPolaskaLinije entity)
		{
			this.SendPropertyChanging();
			entity.Linija = this;
		}
		
		private void detach_DatumPolaskaLinijes(DatumPolaskaLinije entity)
		{
			this.SendPropertyChanging();
			entity.Linija = null;
		}
		
		private void attach_StanicaLinijas(StanicaLinija entity)
		{
			this.SendPropertyChanging();
			entity.Linija = this;
		}
		
		private void detach_StanicaLinijas(StanicaLinija entity)
		{
			this.SendPropertyChanging();
			entity.Linija = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StanicaLinija")]
	public partial class StanicaLinija : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Stanica_StanicaId;
		
		private int _Linija_LinijaID;
		
		private EntityRef<Linija> _Linija;
		
		private EntityRef<Stanica> _Stanica;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStanica_StanicaIdChanging(int value);
    partial void OnStanica_StanicaIdChanged();
    partial void OnLinija_LinijaIDChanging(int value);
    partial void OnLinija_LinijaIDChanged();
    #endregion
		
		public StanicaLinija()
		{
			this._Linija = default(EntityRef<Linija>);
			this._Stanica = default(EntityRef<Stanica>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stanica_StanicaId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Stanica_StanicaId
		{
			get
			{
				return this._Stanica_StanicaId;
			}
			set
			{
				if ((this._Stanica_StanicaId != value))
				{
					if (this._Stanica.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStanica_StanicaIdChanging(value);
					this.SendPropertyChanging();
					this._Stanica_StanicaId = value;
					this.SendPropertyChanged("Stanica_StanicaId");
					this.OnStanica_StanicaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Linija_LinijaID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Linija_LinijaID
		{
			get
			{
				return this._Linija_LinijaID;
			}
			set
			{
				if ((this._Linija_LinijaID != value))
				{
					if (this._Linija.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLinija_LinijaIDChanging(value);
					this.SendPropertyChanging();
					this._Linija_LinijaID = value;
					this.SendPropertyChanged("Linija_LinijaID");
					this.OnLinija_LinijaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Linija_StanicaLinija", Storage="_Linija", ThisKey="Linija_LinijaID", OtherKey="LinijaID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Linija Linija
		{
			get
			{
				return this._Linija.Entity;
			}
			set
			{
				Linija previousValue = this._Linija.Entity;
				if (((previousValue != value) 
							|| (this._Linija.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Linija.Entity = null;
						previousValue.StanicaLinijas.Remove(this);
					}
					this._Linija.Entity = value;
					if ((value != null))
					{
						value.StanicaLinijas.Add(this);
						this._Linija_LinijaID = value.LinijaID;
					}
					else
					{
						this._Linija_LinijaID = default(int);
					}
					this.SendPropertyChanged("Linija");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Stanica_StanicaLinija", Storage="_Stanica", ThisKey="Stanica_StanicaId", OtherKey="StanicaId", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Stanica Stanica
		{
			get
			{
				return this._Stanica.Entity;
			}
			set
			{
				Stanica previousValue = this._Stanica.Entity;
				if (((previousValue != value) 
							|| (this._Stanica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Stanica.Entity = null;
						previousValue.StanicaLinijas.Remove(this);
					}
					this._Stanica.Entity = value;
					if ((value != null))
					{
						value.StanicaLinijas.Add(this);
						this._Stanica_StanicaId = value.StanicaId;
					}
					else
					{
						this._Stanica_StanicaId = default(int);
					}
					this.SendPropertyChanged("Stanica");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Stanica")]
	public partial class Stanica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StanicaId;
		
		private string _nazivGrada;
		
		private decimal _cijenaVoznje;
		
		private EntitySet<StanicaLinija> _StanicaLinijas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStanicaIdChanging(int value);
    partial void OnStanicaIdChanged();
    partial void OnnazivGradaChanging(string value);
    partial void OnnazivGradaChanged();
    partial void OncijenaVoznjeChanging(decimal value);
    partial void OncijenaVoznjeChanged();
    #endregion
		
		public Stanica()
		{
			this._StanicaLinijas = new EntitySet<StanicaLinija>(new Action<StanicaLinija>(this.attach_StanicaLinijas), new Action<StanicaLinija>(this.detach_StanicaLinijas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StanicaId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int StanicaId
		{
			get
			{
				return this._StanicaId;
			}
			set
			{
				if ((this._StanicaId != value))
				{
					this.OnStanicaIdChanging(value);
					this.SendPropertyChanging();
					this._StanicaId = value;
					this.SendPropertyChanged("StanicaId");
					this.OnStanicaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazivGrada", DbType="NVarChar(MAX)")]
		public string nazivGrada
		{
			get
			{
				return this._nazivGrada;
			}
			set
			{
				if ((this._nazivGrada != value))
				{
					this.OnnazivGradaChanging(value);
					this.SendPropertyChanging();
					this._nazivGrada = value;
					this.SendPropertyChanged("nazivGrada");
					this.OnnazivGradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cijenaVoznje", DbType="Decimal(18,2) NOT NULL")]
		public decimal cijenaVoznje
		{
			get
			{
				return this._cijenaVoznje;
			}
			set
			{
				if ((this._cijenaVoznje != value))
				{
					this.OncijenaVoznjeChanging(value);
					this.SendPropertyChanging();
					this._cijenaVoznje = value;
					this.SendPropertyChanged("cijenaVoznje");
					this.OncijenaVoznjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Stanica_StanicaLinija", Storage="_StanicaLinijas", ThisKey="StanicaId", OtherKey="Stanica_StanicaId")]
		public EntitySet<StanicaLinija> StanicaLinijas
		{
			get
			{
				return this._StanicaLinijas;
			}
			set
			{
				this._StanicaLinijas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_StanicaLinijas(StanicaLinija entity)
		{
			this.SendPropertyChanging();
			entity.Stanica = this;
		}
		
		private void detach_StanicaLinijas(StanicaLinija entity)
		{
			this.SendPropertyChanging();
			entity.Stanica = null;
		}
	}
}
#pragma warning restore 1591
